### PR TITLE
Fetch upstream changes

### PR DESCRIPTION
**Pull request by sergeiivankov**
## Changes

- [ ] All from upstream after 0.23 version (see https://github.com/Peternator7/strum/blob/master/CHANGELOG.md)

Related with https://github.com/SeaQL/sea-schema/pull/103 and https://github.com/SeaQL/sea-orm/pull/1520

### CODE REVIEW

**Review by billy1624 — COMMENTED** [review]
Hey @sergeiivankov, thanks for contributing!!

LGTM! It's time to pull the changes from the upstream.

P.S. @tyt2y3 I think we can merge and publish this to crates.io before the SeaORM 0.12.0 is released.

**Comment by tyt2y3** [comment]
Actually, I wish we can avoid using a forked version.

**Comment by tyt2y3** [comment]
Thank you for the contribution.

I did:
1) create branch and tag for 0.23
2) fetch upstream 0.24
3) rebased on 0.24

So I'd close this PR now.

**Comment by tyt2y3** [comment]
Actually how to pin the commit hash for 0.24.0?

**Comment by billy1624** [comment]
> Actually, I wish we can avoid using a forked version.

Maybe there is a way allowing `sea-orm` depends directly on the original `strum`, https://github.com/SeaQL/sea-orm/pull/1535

**Pull request closed without merging**
